trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '438ee9f7-b421-4f2d-ad7e-0a864d53a237'
  imageRepository: 'taskmanager'
  containerRegistry: 'taskmanager.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: Contabo
    
steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs: 
    secureFile: 'appsettings.Production.json'

- script: |
    cp $(appsettings.secureFilePath) src/Backend/TaskManager.API

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)
