trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '2ae77bfc-5375-42b9-8b25-3cf4e39ef569'
  imageRepository: 'apicashflow'
  containerRegistry: 'apicashflow.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: Contabo
    
steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs: 
    secureFile: 'appsettings.Production.json'

- script: |
    cp $(appsettings.secureFilePath) src/Backend/TaskManager.API

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)
